### PR TITLE
Fix: replace sha and md5 with hashlib

### PR DESCRIPTION
**Pull request by adhintz**

### CODE REVIEW

**Comment by graingert** [comment]
@adhintz this doesn't need `six` so I think it should go into fissix https://github.com/jreese/fissix

**Comment by graingert** [comment]
@jreese thoughts on having this fixer in fissix?

**Comment by jreese** [comment]
Yeah, that seems reasonable.

**Comment by graingert** [comment]
Ok! @adhintz because lib2to3 was deprecated modernize has switched to its maintained fork fissix. Can you make this PR there?

**Pull request closed without merging**
